name: Verificar e Comentar PR

on:
  pull_request:
    paths:
      - '**/*.go'  # Aciona o workflow apenas se arquivos .go forem alterados
  workflow_call:  # Permite que o workflow seja reutilizável

jobs:
  comment-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Converter chave privada para PKCS#8
        run: |
          echo "${{ secrets.GH_KARAVELA_TAGS_PRIVATE_KEY }}" > private_key.pem
          openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private_key.pem -out private_key_pkcs8.pem
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          
      - name: Gerar Token da GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ steps.converter.outputs.private_key }}

      - name: Adicionar comentário ao PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = 'Oi';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
