name: Verificar e Comentar PR

on:
  pull_request:
    paths:
      - '**/*.go'  # Aciona o workflow apenas se arquivos .go forem alterados
  workflow_call:  # Permite que o workflow seja reutilizável

jobs:
  comment-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Gerar Token da GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Adicionar comentário ao PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = 'Oi';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
