name: Verificar e Comentar PR

on:
  pull_request:
    paths:
      - '**/*.go'  # Aciona o workflow apenas se arquivos .go forem alterados

permissions:
  contents: write  # Concede permissões de escrita ao GITHUB_TOKEN

jobs:
  comment-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Adicionar comentário ao PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = 'Oi';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: message
            });
